#!/usr/bin/env bash
tmux new -s "Grider Components" -d
tmux send-keys "cd /home/michu/Projects/grider-components" C-m
tmux send-keys "pm2 start 'node_modules/vite/bin/vite.js' --name grider-components" C-m
tmux send-keys "vx" C-m
tmux send-keys "open localhost:5173" C-m
tmux send-keys "$SHELL" C-m
tmux rename-window "🔮 Terminal"
